server {
    listen 80;
    server_name localhost;
    
    # Declaramos la raíz a nivel global para que aplique a todos los archivos
    root /usr/share/nginx/html;

    location / {
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Regla estricta para el favicon: si no lo encuentra, no hace ruido ni lanza errores
    location = /favicon.ico {
        try_files $uri =204;
        access_log off;
        log_not_found off;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}