USE schoolwaysv2;
GO

CREATE TABLE Roles (RolID INT IDENTITY PRIMARY KEY, NombreRol VARCHAR(20) NOT NULL, Descripcion VARCHAR(100));
CREATE TABLE Usuarios (UsuarioID INT IDENTITY PRIMARY KEY, NombreCompleto VARCHAR(100) NOT NULL, CorreoElectronico VARCHAR(100) NOT NULL UNIQUE, PasswordHash VARCHAR(255) NOT NULL, RolID INT NOT NULL, Telefono VARCHAR(15), FotoURL VARCHAR(500), Estado BIT DEFAULT 1, FechaRegistro DATETIME DEFAULT GETDATE());
CREATE TABLE Vehiculos (VehiculoID INT IDENTITY PRIMARY KEY, Placa VARCHAR(10) NOT NULL UNIQUE, Marca VARCHAR(50), Modelo VARCHAR(50), Anio SMALLINT, Capacidad TINYINT, Color VARCHAR(30), Estado BIT DEFAULT 1, FechaRegistro DATETIME DEFAULT GETDATE());
CREATE TABLE Conductores (ConductorID INT IDENTITY PRIMARY KEY, UsuarioID INT NOT NULL UNIQUE, NumeroLicencia VARCHAR(20), VencimientoLicencia DATE, Estado BIT DEFAULT 1, FechaRegistro DATETIME DEFAULT GETDATE());
CREATE TABLE Rutas (RutaID INT IDENTITY PRIMARY KEY, NombreRuta VARCHAR(100) NOT NULL, Descripcion VARCHAR(255), CapacidadMaxima TINYINT, ConductorID INT, VehiculoID INT, Turno VARCHAR(10) CHECK (Turno IN ('Mañana','Tarde','Ambos')), Estado BIT DEFAULT 1, FechaRegistro DATETIME DEFAULT GETDATE());
CREATE TABLE Padres (PadreID INT IDENTITY PRIMARY KEY, UsuarioID INT NOT NULL UNIQUE, DUI VARCHAR(10), TelefonoPrincipal VARCHAR(15), TelefonoAlterno VARCHAR(15), Estado BIT DEFAULT 1, FechaRegistro DATETIME DEFAULT GETDATE());
CREATE TABLE Alumnos (AlumnoID INT IDENTITY PRIMARY KEY, Nombre VARCHAR(80) NOT NULL, Apellido VARCHAR(80) NOT NULL, FechaNacimiento DATE, Grado VARCHAR(20), Seccion VARCHAR(5), Direccion VARCHAR(255), PuntoReferencia VARCHAR(255), Telefono VARCHAR(15), FotoURL VARCHAR(500), EmailPadre VARCHAR(100), PadreID INT, RutaID INT, Estado BIT DEFAULT 1, FechaIngreso DATETIME DEFAULT GETDATE());
CREATE TABLE Asistencias (AsistenciaID INT IDENTITY PRIMARY KEY, AlumnoID INT NOT NULL, ConductorID INT NOT NULL, RutaID INT NOT NULL, FechaHora DATETIME NOT NULL DEFAULT GETDATE(), TipoEvento VARCHAR(20) CHECK (TipoEvento IN ('Abordó','Bajó','Ausente','AvisóAusencia')), Turno VARCHAR(10) CHECK (Turno IN ('Mañana','Tarde')), Observaciones VARCHAR(255), Estado BIT DEFAULT 1);
CREATE TABLE Notificaciones (NotificacionID INT IDENTITY PRIMARY KEY, UsuarioID INT NOT NULL, Titulo VARCHAR(100) NOT NULL, Mensaje VARCHAR(500) NOT NULL, Tipo VARCHAR(30) CHECK (Tipo IN ('Asistencia','Retraso','Aviso','General')), Leida BIT DEFAULT 0, FechaRegistro DATETIME DEFAULT GETDATE(), Estado BIT DEFAULT 1);
CREATE TABLE UbicacionBus (UbicacionID INT IDENTITY PRIMARY KEY, RutaID INT NOT NULL, Latitud DECIMAL(10,8) NOT NULL, Longitud DECIMAL(11,8) NOT NULL, FechaHora DATETIME NOT NULL DEFAULT GETDATE());

