USE schoolwaysv2;
GO

ALTER TABLE Usuarios ADD CONSTRAINT FK_Usuarios_Roles FOREIGN KEY (RolID) REFERENCES Roles(RolID) ON DELETE NO ACTION;
ALTER TABLE Conductores ADD CONSTRAINT FK_Conductores_Usuarios FOREIGN KEY (UsuarioID) REFERENCES Usuarios(UsuarioID) ON DELETE NO ACTION;
ALTER TABLE Padres ADD CONSTRAINT FK_Padres_Usuarios FOREIGN KEY (UsuarioID) REFERENCES Usuarios(UsuarioID) ON DELETE NO ACTION;
ALTER TABLE Alumnos ADD CONSTRAINT FK_Alumnos_Padres FOREIGN KEY (PadreID) REFERENCES Padres(PadreID) ON DELETE NO ACTION;
ALTER TABLE Alumnos ADD CONSTRAINT FK_Alumnos_Rutas FOREIGN KEY (RutaID) REFERENCES Rutas(RutaID) ON DELETE NO ACTION;
ALTER TABLE Rutas ADD CONSTRAINT FK_Rutas_Conductores FOREIGN KEY (ConductorID) REFERENCES Conductores(ConductorID) ON DELETE NO ACTION;
ALTER TABLE Rutas ADD CONSTRAINT FK_Rutas_Vehiculos FOREIGN KEY (VehiculoID) REFERENCES Vehiculos(VehiculoID) ON DELETE NO ACTION;
ALTER TABLE Asistencias ADD CONSTRAINT FK_Asistencias_Alumnos FOREIGN KEY (AlumnoID) REFERENCES Alumnos(AlumnoID) ON DELETE NO ACTION;
ALTER TABLE Asistencias ADD CONSTRAINT FK_Asistencias_Conductores FOREIGN KEY (ConductorID) REFERENCES Conductores(ConductorID) ON DELETE NO ACTION;
ALTER TABLE Asistencias ADD CONSTRAINT FK_Asistencias_Rutas FOREIGN KEY (RutaID) REFERENCES Rutas(RutaID) ON DELETE NO ACTION;
ALTER TABLE Notificaciones ADD CONSTRAINT FK_Notificaciones_Usuarios FOREIGN KEY (UsuarioID) REFERENCES Usuarios(UsuarioID) ON DELETE NO ACTION;
ALTER TABLE UbicacionBus ADD CONSTRAINT FK_UbicacionBus_Rutas FOREIGN KEY (RutaID) REFERENCES Rutas(RutaID) ON DELETE NO ACTION;
